import type { ChatToolCategory, ChatToolSource, ChatToolUiKind } from "./tool-types";

export interface CanonicalToolInventoryEntry {
	name: string;
	sourceOfTruth: ChatToolSource;
	category: ChatToolCategory;
	uiKind: ChatToolUiKind;
	claudeImplementation: string;
	codallyReference?: string;
	status: "implemented" | "stubbed";
	notes?: string;
}

// Claude remains the canonical source of truth for behavior and naming.
// Codally references only inform renderer structure or richer result presentation.
export const CANONICAL_TOOL_INVENTORY: CanonicalToolInventoryEntry[] = [
	{
		name: "Agent",
		sourceOfTruth: "claude",
		category: "advanced",
		uiKind: "task",
		claudeImplementation: ".sources/claude/tools/AgentTool/AgentTool.ts",
		status: "implemented",
		notes: "Local runtime renders subagent requests in a task card but does not launch nested agents yet.",
	},
	{
		name: "AskUserQuestion",
		sourceOfTruth: "claude",
		category: "planning",
		uiKind: "question",
		claudeImplementation: ".sources/claude/tools/AskUserQuestionTool/AskUserQuestionTool.ts",
		codallyReference:
			".sources/codally/src/vs/workbench/contrib/chat/browser/widget/chatContentParts/chatQuestionCarouselPart.ts",
		status: "implemented",
		notes: "Rendered as a local question card and pauses the loop for a user reply.",
	},
	{
		name: "Bash",
		sourceOfTruth: "claude",
		category: "shell",
		uiKind: "command",
		claudeImplementation: ".sources/claude/tools/BashTool/BashTool.tsx",
		codallyReference:
			".sources/codally/src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts",
		status: "implemented",
	},
	{
		name: "Config",
		sourceOfTruth: "claude",
		category: "workflow",
		uiKind: "json",
		claudeImplementation: ".sources/claude/tools/ConfigTool/ConfigTool.ts",
		status: "stubbed",
	},
	{
		name: "Edit",
		sourceOfTruth: "claude",
		category: "filesystem",
		uiKind: "input_output",
		claudeImplementation: ".sources/claude/tools/FileEditTool/FileEditTool.ts",
		codallyReference:
			".sources/codally/src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatStrReplaceDiffPart.ts",
		status: "implemented",
	},
	{
		name: "EnterPlanMode",
		sourceOfTruth: "claude",
		category: "planning",
		uiKind: "text",
		claudeImplementation: ".sources/claude/tools/EnterPlanModeTool/EnterPlanModeTool.ts",
		status: "stubbed",
	},
	{
		name: "EnterWorktree",
		sourceOfTruth: "claude",
		category: "advanced",
		uiKind: "text",
		claudeImplementation: ".sources/claude/tools/EnterWorktreeTool/EnterWorktreeTool.ts",
		status: "stubbed",
	},
	{
		name: "ExitPlanMode",
		sourceOfTruth: "claude",
		category: "planning",
		uiKind: "text",
		claudeImplementation: ".sources/claude/tools/ExitPlanModeTool/ExitPlanModeV2Tool.ts",
		status: "stubbed",
	},
	{
		name: "ExitWorktree",
		sourceOfTruth: "claude",
		category: "advanced",
		uiKind: "text",
		claudeImplementation: ".sources/claude/tools/ExitWorktreeTool/ExitWorktreeTool.ts",
		status: "stubbed",
	},
	{
		name: "Glob",
		sourceOfTruth: "claude",
		category: "search",
		uiKind: "file_list",
		claudeImplementation: ".sources/claude/tools/GlobTool/GlobTool.ts",
		codallyReference:
			".sources/codally/src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatResultListSubPart.ts",
		status: "implemented",
	},
	{
		name: "Grep",
		sourceOfTruth: "claude",
		category: "search",
		uiKind: "input_output",
		claudeImplementation: ".sources/claude/tools/GrepTool/GrepTool.ts",
		codallyReference:
			".sources/codally/src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatInputOutputMarkdownProgressPart.ts",
		status: "implemented",
	},
	{
		name: "LSP",
		sourceOfTruth: "claude",
		category: "advanced",
		uiKind: "json",
		claudeImplementation: ".sources/claude/tools/LSPTool/LSPTool.ts",
		status: "stubbed",
	},
	{
		name: "ListMcpResourcesTool",
		sourceOfTruth: "claude",
		category: "mcp",
		uiKind: "file_list",
		claudeImplementation: ".sources/claude/tools/ListMcpResourcesTool/ListMcpResourcesTool.ts",
		status: "stubbed",
	},
	{
		name: "NotebookEdit",
		sourceOfTruth: "claude",
		category: "filesystem",
		uiKind: "input_output",
		claudeImplementation: ".sources/claude/tools/NotebookEditTool/NotebookEditTool.ts",
		codallyReference:
			".sources/codally/src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatInputOutputMarkdownProgressPart.ts",
		status: "implemented",
	},
	{
		name: "Read",
		sourceOfTruth: "claude",
		category: "filesystem",
		uiKind: "input_output",
		claudeImplementation: ".sources/claude/tools/FileReadTool/FileReadTool.ts",
		codallyReference:
			".sources/codally/src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatInputOutputMarkdownProgressPart.ts",
		status: "implemented",
	},
	{
		name: "ReadMcpResourceTool",
		sourceOfTruth: "claude",
		category: "mcp",
		uiKind: "input_output",
		claudeImplementation: ".sources/claude/tools/ReadMcpResourceTool/ReadMcpResourceTool.ts",
		status: "stubbed",
	},
	{
		name: "RemoteTrigger",
		sourceOfTruth: "claude",
		category: "workflow",
		uiKind: "text",
		claudeImplementation: ".sources/claude/tools/RemoteTriggerTool/RemoteTriggerTool.ts",
		status: "stubbed",
	},
	{
		name: "SendMessage",
		sourceOfTruth: "claude",
		category: "workflow",
		uiKind: "text",
		claudeImplementation: ".sources/claude/tools/SendMessageTool/SendMessageTool.ts",
		status: "stubbed",
	},
	{
		name: "SendUserMessage",
		sourceOfTruth: "claude",
		category: "workflow",
		uiKind: "text",
		claudeImplementation: ".sources/claude/tools/BriefTool/BriefTool.ts",
		status: "implemented",
		notes: "Claude canonical name is SendUserMessage; legacy alias Brief retained only for compatibility.",
	},
	{
		name: "Skill",
		sourceOfTruth: "claude",
		category: "workflow",
		uiKind: "text",
		claudeImplementation: ".sources/claude/tools/SkillTool/SkillTool.ts",
		status: "stubbed",
	},
	{
		name: "StructuredOutput",
		sourceOfTruth: "claude",
		category: "workflow",
		uiKind: "json",
		claudeImplementation: ".sources/claude/tools/SyntheticOutputTool/SyntheticOutputTool.ts",
		status: "implemented",
	},
	{
		name: "TaskCreate",
		sourceOfTruth: "claude",
		category: "tasks",
		uiKind: "todo_list",
		claudeImplementation: ".sources/claude/tools/TaskCreateTool/TaskCreateTool.ts",
		status: "implemented",
	},
	{
		name: "TaskGet",
		sourceOfTruth: "claude",
		category: "tasks",
		uiKind: "todo_list",
		claudeImplementation: ".sources/claude/tools/TaskGetTool/TaskGetTool.ts",
		status: "implemented",
	},
	{
		name: "TaskList",
		sourceOfTruth: "claude",
		category: "tasks",
		uiKind: "todo_list",
		claudeImplementation: ".sources/claude/tools/TaskListTool/TaskListTool.ts",
		status: "implemented",
	},
	{
		name: "TaskOutput",
		sourceOfTruth: "claude",
		category: "tasks",
		uiKind: "task",
		claudeImplementation: ".sources/claude/tools/TaskOutputTool/TaskOutputTool.ts",
		status: "implemented",
		notes: "Shows a task-output card explaining that delegated output is not yet persisted locally.",
	},
	{
		name: "TaskStop",
		sourceOfTruth: "claude",
		category: "workflow",
		uiKind: "text",
		claudeImplementation: ".sources/claude/tools/TaskStopTool/TaskStopTool.ts",
		status: "implemented",
	},
	{
		name: "TaskUpdate",
		sourceOfTruth: "claude",
		category: "tasks",
		uiKind: "todo_list",
		claudeImplementation: ".sources/claude/tools/TaskUpdateTool/TaskUpdateTool.ts",
		status: "implemented",
	},
	{
		name: "TeamCreate",
		sourceOfTruth: "claude",
		category: "advanced",
		uiKind: "text",
		claudeImplementation: ".sources/claude/tools/TeamCreateTool/TeamCreateTool.ts",
		status: "stubbed",
	},
	{
		name: "TeamDelete",
		sourceOfTruth: "claude",
		category: "advanced",
		uiKind: "text",
		claudeImplementation: ".sources/claude/tools/TeamDeleteTool/TeamDeleteTool.ts",
		status: "stubbed",
	},
	{
		name: "TodoWrite",
		sourceOfTruth: "claude",
		category: "tasks",
		uiKind: "todo_list",
		claudeImplementation: ".sources/claude/tools/TodoWriteTool/TodoWriteTool.ts",
		status: "implemented",
	},
	{
		name: "ToolSearch",
		sourceOfTruth: "claude",
		category: "workflow",
		uiKind: "file_list",
		claudeImplementation: ".sources/claude/tools/ToolSearchTool/ToolSearchTool.ts",
		status: "implemented",
	},
	{
		name: "WebFetch",
		sourceOfTruth: "claude",
		category: "web",
		uiKind: "input_output",
		claudeImplementation: ".sources/claude/tools/WebFetchTool/WebFetchTool.ts",
		status: "implemented",
	},
	{
		name: "WebSearch",
		sourceOfTruth: "claude",
		category: "web",
		uiKind: "file_list",
		claudeImplementation: ".sources/claude/tools/WebSearchTool/WebSearchTool.ts",
		status: "implemented",
	},
	{
		name: "Write",
		sourceOfTruth: "claude",
		category: "filesystem",
		uiKind: "input_output",
		claudeImplementation: ".sources/claude/tools/FileWriteTool/FileWriteTool.ts",
		codallyReference:
			".sources/codally/src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatInputOutputMarkdownProgressPart.ts",
		status: "implemented",
	},
];
